## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [253]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['acertos_mat'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['acertos_por'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['acertos_geo'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['acertos_ing'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['acertos_his'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['acertos_fis'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['acertos_qui'])

df_concat = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
df_concat

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui
0,6,7,7,3,1,8,3
1,19,10,0,0,0,11,8
2,14,16,0,5,7,4,4
3,10,7,3,4,0,0,8
4,7,2,2,7,0,9,3
...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3
96,8,1,4,6,1,4,3
97,23,5,0,2,4,1,5
98,0,10,3,1,5,10,11
99,11,15,0,1,6,7,2

In [269]:
# 1) Seu código aqui

df_percent = pd.DataFrame(columns=['percentual_mat'])
df_percent['percentual_mat'] = df_concat['acertos_mat'] / 24
df_percent['percentual_por'] = df_concat['acertos_por'] / 18
df_percent['percentual_geo'] = df_concat['acertos_geo'] / 8
df_percent['percentual_ing'] = df_concat['acertos_ing'] / 8
df_percent['percentual_his'] = df_concat['acertos_his'] / 8
df_percent['percentual_fis'] = df_concat['acertos_fis'] / 12
df_percent['percentual_qui'] = df_concat['acertos_qui'] / 12

df_percent

,percentual_mat,percentual_por,percentual_geo,percentual_ing,percentual_his,percentual_fis,percentual_qui
0,0.250000,0.388889,0.875,0.375,0.125,0.666667,0.250000
1,0.791667,0.555556,0.000,0.000,0.000,0.916667,0.666667
2,0.583333,0.888889,0.000,0.625,0.875,0.333333,0.333333
3,0.416667,0.388889,0.375,0.500,0.000,0.000000,0.666667
4,0.291667,0.111111,0.250,0.875,0.000,0.750000,0.250000
...,...,...,...,...,...,...,...
95,0.250000,0.222222,0.875,0.125,0.500,0.750000,0.250000
96,0.333333,0.055556,0.500,0.750,0.125,0.333333,0.250000
97,0.958333,0.277778,0.000,0.250,0.500,0.083333,0.416667
98,0.000000,0.555556,0.375,0.125,0.625,0.833333,0.916667
99,0.458333,0.833333,0.000,0.125,0.750,0.583333,0.166667

In [411]:
df_concat['soma_total'] = pd.DataFrame(np.sum(df_concat.T), columns=['total_acertos'])
df_concat['soma_total']

C:\Users\enzob\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

0     36
1     49
2     51
3     33
4     31
      ..
95    35
96    28
97    41
98    41
99    43
Name: soma_total, Length: 100, dtype: int64

In [279]:
percent_geral = soma_tot / 90
percent_geral

    total_acertos
0        0.388889
1        0.533333
2        0.555556
3        0.355556
4        0.333333
..            ...
95       0.377778
96       0.300000
97       0.444444
98       0.444444
99       0.466667

[100 rows x 1 columns]

In [283]:
soma_tot['aprovados'] = 0
soma_tot.loc[soma_tot['total_acertos'] > 45, 'aprovados'] = 1
alunos_aprovados = np.sum(soma_tot['aprovados'])
alunos_aprovados

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [349]:
df_concat['reprovados'] = 0
df_concat.loc[df_concat['acertos_mat'] == 0, 'reprovados'] = 1
df_concat.loc[df_concat['acertos_fis'] == 0, 'reprovados'] = 1
df_concat.loc[df_concat['acertos_qui'] == 0, 'reprovados'] = 1

df_rep = pd.DataFrame(df_concat.loc[df_concat['reprovados'] == 1])
df_rep

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui,reprovados
3,10,7,3,4,0,0,8,1
6,6,0,7,7,5,0,4,1
10,10,8,3,2,1,7,0,1
12,20,8,3,7,1,0,3,1
14,7,11,1,7,1,4,0,1
20,23,11,6,5,6,2,0,1
25,0,4,7,4,0,4,8,1
26,11,14,6,2,7,0,0,1
27,21,13,1,5,7,3,0,1
33,14,8,0,5,6,6,0,1
35,11,14,6,3,3,0,11,1
49,8,1,1,0,1,0,8,1
56,7,6,7,5,6,0,8,1
65,1,8,2,4,3,0,6,1
66,5,4,3,6,3,0,10,1
72,11,16,3,4,7,0,9,1
73,1,16,2,4,3,0,11,1
74,9,11,0,7,5,7,0,1
84,15,1,0,5,1,0,4,1
89,23,11,7,7,6,9,0,1
92,14,10,1,6,1,8,0,1
94,0,5,2,6,1,3,8,1
98,0,10,3,1,5,10,11,1

In [351]:
alunos_rep = np.sum(df_rep['reprovados'])
alunos_rep

23

In [379]:
media_geo = np.sum(df_rep['acertos_geo']) / len(df_rep)
media_his = np.sum(df_rep['acertos_his']) / len(df_rep)

media_his_geo = {'media_historia': media_his, 'media_geografia': media_geo}
media_his_geo

{'media_historia': 3.4347826086956523, 'media_geografia': 3.217391304347826}

In [417]:
df_concat['aprovados'] = 1
df_concat.loc[df_concat['acertos_mat'] == 0, 'aprovados'] = 0
df_concat.loc[df_concat['acertos_fis'] == 0, 'aprovados'] = 0
df_concat.loc[df_concat['acertos_qui'] == 0, 'aprovados'] = 0

df_rest = pd.DataFrame(df_concat.loc[df_concat['aprovados'] == 1])

df_aprov = pd.DataFrame(df_rest.loc[df_rest['soma_total'] > 45])
df_aprov

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui,reprovados,aprovados,soma_total
1,19,10,0,0,0,11,8,0,1,49
2,14,16,0,5,7,4,4,0,1,51
5,20,2,5,3,2,9,9,0,1,51
7,18,4,4,7,7,1,8,0,1,50
8,22,9,2,7,6,5,7,0,1,59
17,21,15,2,2,4,2,6,0,1,53
18,20,4,3,5,3,11,4,0,1,51
24,20,2,7,5,3,11,2,0,1,51
31,15,13,3,1,3,9,10,0,1,55
34,18,14,1,0,6,3,3,0,1,46
36,22,9,6,6,1,4,8,0,1,57
37,19,12,5,7,1,6,2,0,1,53
39,4,16,2,4,6,9,8,0,1,50
40,18,3,6,3,6,5,6,0,1,48
42,20,6,7,7,2,3,3,0,1,49
45,17,10,0,2,6,9,4,0,1,49
48,17,6,0,7,5,9,11,0,1,56
53,14,11,3,4,3,7,3,0,1,46
60,16,8,0,4,4,7,9,0,1,49
62,17,6,2,4,7,1,9,0,1,47
67,21,0,7,2,4,2,10,0,1,47
70,21,14,0,3,5,11,8,0,1,63
71,17,8,7,6,4,2,9,0,1,54
77,15,2,5,7,6,11,7,0,1,54
78,14,16,7,2,7,11,9,0,1,67
80,13,16,5,1,7,2,1,0,1,46
81,22,16,2,0,4,1,10,0,1,56
88,20,1,1,5,7,9,7,0,1,51
93,12,16,5,5,6,6,6,0,1,57

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [421]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-5ed92752-6121-474f-ab37-816918134afc.c000.csv'

In [423]:
# 1) Sua solução aqui
df = pd.read_csv(arquivo, sep=';')
df

HTTPError: HTTP Error 403: Forbidden

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 3) solução alternativa

In [ ]:
# 4)

In [ ]:
# 5)

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [ ]:
# 1)

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 4)

In [ ]:
# 5)